from_latest_tag = false
ignore_merge_commits = false
disable_changelog = true
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks.commit-msg]
script = """#!/usr/bin/env sh
set -e

echo "[Check current commit message]"
cog verify --file $1
"""

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = [
  { signature = "robin roses", username = "comfysage" }
]

[bump_profiles]

[packages]
