[book]
authors = ["isabel roses"]
language = "en"
src = "src"
title = "dotfiles"

[build]
build-dir = "./dist"
create-missing = false

[output.html]
default-theme = "latte"
preferred-dark-theme = "mocha"
git-repository-url = "https://github.com/isabelroses/dotfiles"
# git-repository-icon = "fa-code-fork"
cname = "dotfiles.isabelroses.com"
additional-css = ["./theme/catppuccin.css"]
